# Generated by Django 5.2 on 2025-04-14 14:59

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_productproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[products.validators.validate_file_size]),
        ),
    ]
